apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: sc47z8knw-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sc47z8knw-go 
  name: sc47z8knw-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: sc47z8knw-go 
